{
  "openapi": "3.0.3",
  "info": {
    "title": "Todolist RESTful API",
    "version": "1.0",
    "description": "Todolist RESTful API",
    "termsOfService": "https://github.com/DaudHidayatR",
    "contact": {
      "name": "Daud Hidayat Ramadhan",
      "email": "daud28ramadhan@gmail.com",
      "url": "https://github.com/DaudHidayatR"
    },
    "license": {
      "name": "Apache-2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "servers": [
    {
      "description": "Todolist RESTful API",
      "url": "https://{environment}.daud.com/DaudHidayatR",
      "variables": {
        "environment": {
          "description": "Server Environment",
          "default": "dev",
          "enum": [
            "dev",
            "qa",
            "prod"
          ]
        }
      }
    }

  ],
  "externalDocs": {
    "description": "Linkendin daud hidayat ramadhan",
    "url": "https://www.linkedin.com/in/daud-hidayat-ramadhan-98a5251b1"
  },
  "paths": {
    "/todolist": {
      "get":{
        "tags": ["Todolist"],
        "summary": "Get all todolist",
        "description": "Get all active todolist by default",
        "parameters": [
          {
            "name": "include done",
            "in": "query",
            "required": false,
            "description": "Include done todolist",
            "schema": {
              "type": "boolean",
              "default": true,
              "nullable": true
            }
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "description": "Filter todolist by name",
            "schema": {
              "type": "string",
              "nullable": false,
              "minLength": 1,
              "maxLength": 100
            },
            "examples": {
              "java" : {
                "description": "Example of todolist name Java",
                "value": "JAVA"
              },
              "php": {
                "description": "Example of todolist name PHP",
                "value": "PHP"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success get all todolist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "priority": {
                        "type": "number",
                        "format": "int32"
                      },
                      "tags": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Success get all todolist",
                    "value": [
                      {
                        "id": "1",
                        "name": "JAVA",
                        "priority": 1,
                        "tags": [
                          "java",
                          "programming"
                        ]
                      },
                      {
                        "id": "2",
                        "name": "PHP",
                        "priority": 2,
                        "tags": [
                          "php",
                          "programming"
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
        "post":{
          "tags": ["Todolist"],
          "summary": "Create new todolist",
          "description": "Create new todolist to database",
          "requestBody": {
            "required": true,
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string",
                      "minLength": 1,
                      "required": true
                    },
                    "priority": {
                      "type": "integer",
                      "format": "int32",
                      "required": true,
                      "default": 1
                    },
                    "tags": {
                      "type": "array",
                      "required": false,
                      "minItems": 1,
                      "items": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 100
                      }
                    }
                  }
                },
                "examples": {
                  "java" : {
                    "description": "Example of todolist name Java",
                    "value": {
                      "name": "JAVA",
                      "priority": 1,
                      "tags": [
                        "java",
                        "programming"
                      ]
                    }
                  },
                  "php": {
                    "description": "Example of todolist name PHP",
                    "value": {
                      "name": "PHP",
                      "priority": 2,
                      "tags": [
                        "php",
                        "programming"
                      ]
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Success create new todolist",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "priority": {
                        "type": "number",
                        "format": "int32"
                      },
                      "tags": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "examples": {
                    "Java": {
                      "description": "Success create new todolist java",
                      "value": {
                        "id": "1",
                        "name": "JAVA",
                        "priority": 1,
                        "tags": [
                          "java",
                          "programming"
                        ]
                      }
                    },
                    "php": {
                      "description": "Success create new todolist php",
                      "value": {
                        "id": "3",
                        "name": "PHP",
                        "priority": 1,
                        "tags": [
                          "php",
                          "programming"
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }

    },
    "/todolist/{todolistId}": {
      "put": {
        "tags": ["Todolist"],
        "summary": "Update existing todolist",
        "description": "Update existing todolist to database",
        "parameters": [
          {
            "name": "todolistId",
            "in": "path",
            "required": true,
            "description": "Todolist for updated",
            "schema": {
              "type": "string"
            },
            "examples": {
              "java" : {
                "description": "Example of todolist id Java",
                "value": "1"
              },
              "php": {
                "description": "Example of todolist id PHP",
                "value": "2"
              }
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 1,
                    "required": true
                  },
                  "priority": {
                    "type": "integer",
                    "format": "int32",
                    "required": true,
                    "default": 1
                  },
                  "tags": {
                    "type": "array",
                    "required": false,
                    "minItems": 1,
                    "items": {
                      "type": "string",
                      "minLength": 1,
                      "maxLength": 100
                    }
                  }
                }
              },
              "examples": {
                "java" : {
                  "description": "Example of todolist name Java",
                  "value": {
                    "name": "JAVA",
                    "priority": 1,
                    "tags": [
                      "java",
                      "programming"
                    ]
                  }
                },
                "php": {
                  "description": "Example of todolist name PHP",
                  "value": {
                    "name": "PHP",
                    "priority": 2,
                    "tags": [
                      "php",
                      "programming"
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success update todolist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "priority": {
                      "type": "number",
                      "format": "int32"
                    },
                    "tags": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "Java": {
                    "description": "Success update todolist java",
                    "value": {
                      "id": "1",
                      "name": "JAVA",
                      "priority": 1,
                      "tags": [
                        "java",
                        "programming"
                      ]
                    }
                  },
                  "php": {
                    "description": "Success update todolist php",
                    "value": {
                      "id": "3",
                      "name": "PHP",
                      "priority": 1,
                      "tags": [
                        "php",
                        "programming"
                      ]
                    }
                  }
                }
              }
            }

          }
        }
      },
      "delete": {
        "tags": ["Todolist"],
        "summary": "Delete existing todolist",
        "description": "Delete existing todolist in database",
        "parameters": [
          {
            "name": "todolistId",
            "in": "path",
            "required": true,
            "description": "Todolist Id for deleted",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success delete todolist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Success delete todolist",
                    "value": {
                      "success": true
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Failed delete not found todolist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "fail": {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "failed": {
                    "description": "Failed delete todolist",
                    "value": {
                      "success": false
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
    "components": {
      "parameters": {
          "todolistId": {
            "name": "todolistId",
            "in": "path",
            "required": true,
            "description": "Todolist for updated",
            "schema": {
              "type": "string"
            },
            "examples": {
              "java" : {
                "description": "Example of todolist id Java",
                "value": "1"
              },
              "php": {
                "description": "Example of todolist id PHP",
                "value": "2"
              }
            }
          }

      },
      "schemas": {
          "Todolist": {
              "type": "object",
              "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "number",
                    "format": "int32"
                },
                "tags": {
                    "type": "array",
                    "items": {
                    "type": "string"
                    }
                }
              }
          },
          "CreateOrUpdateTodolist": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "priority": {
                "type": "number",
                "format": "int32"
              },
              "tags": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          },
          "ArrayTodolist": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "priority": {
                  "type": "number",
                  "format": "int32"
                },
                "tags": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
    }
}
